
title: Xuan FENG
author: Xuan FENG
chinese_name: 丰轩
email: xuafeng@microsoft.com
url: https://xuafeng.win
baseurl: /cv
description: Researcher at MSR.

theme_config:
  appearance: "auto" 
  back_home_text: "../" 
  date_format: "%Y-%m-%d"
  show_description: true

sass:
  style: :compressed

plugins:
  - jekyll-feed
  - jekyll-seo-tag

collections:
  notes:
    output: true
    permalink: /research/:name/

defaults:
  - scope:
      path: ""
      type: "notes"
    values:
      layout: note
