
title: Xuan Feng
author: Xuan Feng
chinese_name: 丰轩
email: xuafeng@microsoft.com
url: https://xuafeng.win
baseurl: /cv
description: Researcher at Microsoft Research Asia - Vancouver working on future agent systems, system intelligence, and AI for security.

theme_config:
  appearance: "auto" 
  back_home_text: "../" 
  date_format: "%Y-%m-%d"
  show_description: true

sass:
  style: :compressed

plugins:
  - jekyll-feed
  - jekyll-seo-tag

collections:
  notes:
    output: true
    permalink: /garden/:name/

defaults:
  - scope:
      path: ""
      type: "notes"
    values:
      layout: note
